aws authentication fixes
numaproj-contrib/aws-sqs-source-go pull request #9
Opened 2023-11-29 08:07 UTC by shubhamdixit863

2023-11-29 17:29 UTC, vigith requested changes

2023-11-29 17:29 UTC, vigith commented on go.mod
>  	github.com/aws/aws-sdk-go v1.46.3
let's deprecate the old AWS Go SDK.

2023-11-30 06:13 UTC, whynowy commented on pkg/sqs/sqs.go
> +	count, err := s.getApproximateMessageCount(approximateNumberOfMessagesNotVisible)
Does this query return the total invisible message number read by all the clients, or only by the current client? If it's the first case, it means there will be only one client working even there are multiple replicas?

2023-11-30 14:59 UTC, KeranYang commented on main.go
> +	queue, err := getQueueUrl(client, queueName, ctx)
```suggestion
	queue, err := client.GetQueueUrl(ctx, &awsSqs.GetQueueUrlInput{QueueName: aws.String(queueName)})
```

`getQueueUrl` is a [shallow](https://medium.com/@alexturdean/shallow-functions-the-silent-killer-of-good-software-527a29ab56c9) function. Please remove it.

2023-11-30 14:59 UTC, KeranYang commented on pkg/sqs/sqs.go
> +	waitTimeSeconds                       = 20 // WaitTimeSeconds specifies the time (in seconds) the call waits for a message to arrive in the queue before returning. If a message arrives, the call ret
```suggestion
	maxNumberOfMessages                   = 10 // maxNumberOfMessages is messages to return From SQS Valid values: 1 to 10. Default: 1
	waitTimeSeconds                       = 20 // waitTimeSeconds specifies the time (in seconds) the call waits for a message to arrive in the queue before returning. If a message arrives, the call returns early; if not and the time expires, it returns an empty message list.
```

2023-11-30 14:59 UTC, KeranYang commented on pkg/sqs/sqs.go
> +// The queryType can be either "approximateNumberOfMessages" or "ApproximateNumberOfMessagesNotVisible".
```suggestion
// The queryType can be either "approximateNumberOfMessages" or "approximateNumberOfMessagesNotVisible".
```

2023-11-30 14:59 UTC, KeranYang commented on pkg/sqs/sqs.go
> +	count, err := s.getApproximateMessageCount(approximateNumberOfMessagesNotVisible)
+1. According to [aws doc](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html), it seems the first case.

2023-12-05 13:48 UTC, KeranYang approved these changes

2023-12-05 15:02 UTC, vigith approved these changes
please fix the DCO

2023-12-05 16:00 UTC, merged